app/lib/utils.py
app/models.py
config_template.py

Tested in our environment, thanks for this great frontend.

Add Active directory authentication and Timeout for large zone

---

README.md

Fixing documentation in README.md

Fix 'config_template.py' copy snippet in README.

---

app/templates/admin.html
app/templates/admin_history.html
app/templates/admin_manageuser.html
app/templates/dashboard.html
app/templates/domain.html
app/templates/domain_add.html
app/templates/domain_management.html
app/templates/user_profile.html

This changes the breadcrumb link for 'Home' to be generated by Flask instead of static.

Fix 'Home' breadcrumb when running in a subdirectory. Fixes #26

---

app/static/admin/layout2/css/custom.css
app/static/admin/pages/scripts/table-editable.js

Break up long data fields. Fixes #28.

---

app/models.py
app/templates/login.html
app/views.py
config_template.py

Hello!
I made some improvements in ldap_filter and login page

Ldap_filter and login page setting

---

app/static/custom/js/custom.js
app/templates/dashboard.html
app/templates/domain.html
app/views.py

Fixed three issues identified in first round of testing by @ngoduykhanh

Results of first round of testing

---

app/static/admin/pages/scripts/my-button-action.js

This fixes #40. @ngoduykhanh please review.

Reload dashboard only after domain deletion finished. Fixes #40.

---

README.md

Documentation change based on discussion in #44

Fix some spelling mistakes in README. Add supported version information.

---

app/models.py

Hi,
Thanks for creating pdns-admin!
We have 1300+ domains and the sync that is preformed each time you view the domain list was terribly slow for us. The main problem was that each domain was updated each time, regardless whether there were actual changes or not. Besides that, each domain was queried from the db, but the entire list was already loaded at line 427.
So I reworked the domain list to a dict in line 429, and made the sql updates dependent on actual changes / additions.
Please consider these changes for inclusion, as I think it may help others too. 
Thanks,
Alex.

Optimize domain sync

---

app/models.py
app/templates/domain_management.html
app/views.py

Per domain settings

---

app/templates/admin_history.html
app/templates/admin_manageuser.html
app/templates/admin_settings.html
app/templates/base.html
app/templates/dashboard.html
app/templates/domain.html
app/templates/domain_management.html
app/templates/user_profile.html

Scriptroot fix

---

config_template_docker.py
create_db.py
docker-compose.yml

Add docker-compose.yml file to easily dev with Docker. For this, I have to improve create_db.py to be idempotent to safety rerun it when start container.

Add docker-compose.yml file

---

app/lib/utils.py
app/templates/base.html
app/templates/user_profile.html
app/views.py

Use gravatar for user who doesn't specify a avatar.
ref: #66

Add Gravatar

---

.gitignore
app/__init__.py
app/templates/login.html
app/views.py
config_template.py
requirements.txt

this PR introduces github oauth2 login by @cmgs, I did some minor improvements on code style.
Please tell us if you're happy with the functionality, or if this PR needs more work.

support github oauth2 login

---

app/templates/domain_management.html

For ex: mount = /pdsn-admin=run.py

Fix domain delete action if uwsgi path mount is not /

---

app/lib/utils.py

This pull request fixes #105 .  Let me know if you have any further questions comments or suggestions.

Fix NoneType error when logging in with AD

---

app/static/custom/js/custom.js
app/templates/domain.html

Previously this caused the newly added record to either appear at the bottom, or not appear at all. Now it will always be added at the top, and whatever search present is cleared.
Fixes #94 and #115.

Fix issues when adding a record, and sort and/or search is involved

---

app/models.py

this fix a bug in `create_local_user`, which breaks github login.
the commit is line 271, the rest is whitespace stripping.

set user object id after created

---

app/static/custom/css/custom.css
app/static/custom/js/custom.js
app/templates/admin_history.html
app/templates/dashboard.html

Pretty history details

---

app/models.py

authored by @CMGS , this commit intends to make `models.py` more pythonic

models refactoring

---

app/templates/domain_management.html

Fixes #98 
However it would be nice to get error message if the delete does not work.

Fix issue with deleting domain

---

app/static/custom/js/custom.js

Fixes #176. Tested briefly with my data.

Fix for #176

---

app/templates/domain.html

The record helper for the SRV record didn't show up.

Corrected SRV record helper not showing

---

app/models.py
app/templates/base.html
app/templates/dashboard.html
app/templates/domain.html
app/templates/domain_add.html
app/templates/template.html
app/templates/template_add.html
app/templates/template_edit.html
app/views.py
create_db.py

As a basis, I used the @ivanfilippov code. I asked permission of the author of the code for this.
I added the ability to create a zone template, the ability to clone an existing zone in a template, and create a zone based on the template.

Adding zone template functionality

---

app/models.py
app/views.py

if hostname is @.domain.tld (provided by the ddns-client) the DNS type has to be A or AAAA, which is checked in the exists method of Record.
Thus CNAME (or other) updates are still possible, and ipv6 records can also be updated.

re-fix root domain record update via dyndns

---

app/lib/utils.py
app/templates/admin_history.html
app/views.py

- Cloning a zone to a template did not remove the domain part from the records
- Stripping of the domain string was not limited to the the domain part of a name
- Fix clear history (firefox)

Some fixes and improvements 

---

app/views.py

A poorly copy/pasted check in #273 causes problems when trying to delete a user.
Fix that check so deleting a user starts working again.

Fix user deletion 

---

app/models.py

For DNSSEC enabled zones to function correctly, they need to be rectified on update.
This changes the DNSSEC enable/disable code to set API-RECTIFY:
To `true` when activating DNSSEC on a domain
To `false` when deactivating DNSSEC on a domain
With this, PowerDNS promises to handle the needed rectifications.
Aims to fix #268 
Fixed a different problem in the process, where an exception is thrown (and caught) in the DNSSEC delete code, because utils.fetch_json() returns a BOOL on the DELETE request, rather than a json.

Automatically rectify DNSSEC enabled zones

---

configs/development.py
docker-compose.yml
docker/PowerDNS-Admin/entrypoint.sh

Fixes for a docker-compose working out of the box

---

docker-compose.yml

Expose pdns default port 53 via UDP

---

app/models.py
config_template.py
configs/development.py

This PR is to fix LDAP password checking when validate user.
Also fix for #294 and #323

Adjustment in LDAP authentication

---

update_zones.py

A CLI Script to update list of domains instead from the UI. Can be useful for people who want to execute updates from a cronjob

CLI script to update zone list

---

app/models.py
app/templates/admin_edituser.html
app/templates/admin_manageuser.html
app/views.py

Fixes #325 
Update user management feature to allow editing user details directly in the admin user interface.
Also added an option to reset the two factor authentication data of a user, for when that's needed (lost device, technical issues etc).

Add option to edit users from the comfort of the UI

---

.lgtm.yml
app/__init__.py
app/decorators.py
app/lib/log.py
app/lib/utils.py
app/models.py
app/oauth.py
app/static/custom/js/custom.js
app/templates/admin_history.html
app/templates/admin_manageuser.html
app/templates/admin_setting_authentication.html
app/templates/admin_setting_basic.html
app/templates/admin_setting_pdns.html
app/templates/base.html
app/templates/dashboard.html
app/templates/dashboard_domain.html
app/templates/domain.html
app/templates/domain_management.html
app/templates/template.html
app/templates/template_edit.html
app/templates/user_profile.html
app/views.py
docker/PowerDNS-Admin/entrypoint.sh
init_data.py
migrations/versions/1274ed462010_remove_all_settings_in_the_db.py
migrations/versions/4a666113c7bb_add_operator_role.py
run.py
update_zones.py

In this PR:
- Add `Operator` role.
- Adjust ldap group policy to to have Operator role.
- Change the way of setting user role in User Management
- Adjust the code as LGTM.com suggestion
- Add options to allow user to create domain #130
- Fix domain template record modification #346
This PR is to enhance the security which mentioned in #342. PDA will have 3 roles:
- Administrator: Have full access
- Operator: Have full access except: PDNS and Authentication settings. Not able to edit Administrator users.
- User: Have access to granted domain only.

Adding Operator role and Code adjustment

---

app/views.py

Make a redirection to previous page after logged in

---

app/templates/domain.html
app/templates/template_edit.html

Change SOA expiry placeholder value

---

app/views.py

Fix #411 to use with APPLICATION_ROOT Flask config variable

Fix login redirection when submounted

---

app/templates/register.html
app/views.py

Fix #422. Also separate the code for login / register routing.

Fix disabling the user registration form

---

configs/development.py

logging doesn't work with relative path...

Fix logging path, needs absolute path

---

app/__init__.py
app/customboxes.py
app/templates/dashboard.html
app/views.py

Separate Tabs for Reverse Zones (IP4 & IP6)
Hi @ngoduykhanh,
Im sry for the Prevous Pull Request, here is the correct one.
Cheers :-)

Separate Tabs for Reverse Zones (IP4 & IP6) (Corrected)

---

app/templates/domain.html

Added a edit popup for TLSA records like the ones for SRV and MX.

Added TLSA Popup

---

app/templates/user_profile.html

Fixes spelling error on the Authentication tab of the user profile.

Fix typo in user profile template

---

app/templates/domain.html
app/templates/template_edit.html

Also add small adjustment to warn user on un-saved record when applying the changes.

Fix domain datatable. #468

---

app/blueprints/api.py
app/swagger-spec.yaml

added API-Endpoint and swagger definition for /sync_domains to update/synchronize domains in background

Added endpoint synchronize domains

---

app/lib/log.py

Timestamp was missing when developing with Docker-compose so we added it.

added TimeStamp to logging

---

app/models.py

added logging to see the amount of entrys in both PDNS and PDNS-Admin database aswell as which domains are getting synched/Updated/deleted

add a more comprehensive logging for domain_update

---

app/models.py

Split method into delete_domain_from_pdnsadmin(), update_pdns_admin_domain(), add_domain_to_powerdns_admin() methods to enhance reusability and better readability.

split up update function add/delete/update

---

powerdnsadmin/models/server.py
powerdnsadmin/routes/admin.py
powerdnsadmin/templates/admin_global_search.html
powerdnsadmin/templates/base.html

Add ability to search zones/recods/comments directly from PDNS API
Feature request: #568

Add PDNS global search feature

---

powerdnsadmin/routes/api.py

This pull request adds history entries to rrset updates and deletes via the api to the history table of PDA.

add history entries for rrsets

---

docker/Dockerfile
docker/entrypoint.sh

* use alpine as base image
* employ multi stage build to get rid of build artefacts

Update dockerfile to reduce image size

---

powerdnsadmin/routes/dashboard.py
powerdnsadmin/templates/dashboard.html
powerdnsadmin/templates/dashboard_domain.html

Fix dashboard domain sorting

---

package.json
powerdnsadmin/assets.py
powerdnsadmin/models/setting.py
powerdnsadmin/routes/admin.py
powerdnsadmin/routes/api.py
powerdnsadmin/routes/dashboard.py
powerdnsadmin/routes/domain.py
powerdnsadmin/routes/index.py
powerdnsadmin/routes/user.py
powerdnsadmin/static/custom/js/custom.js
powerdnsadmin/templates/base.html
tests/unit/zone/test_admin_apikey.py
yarn.lock

This feature to show session timeout warning popup when user's session has 1 minute left.
This feature can be enabled/disabled via setting. The default is ON.
FR: #457

Warn session timeout

---

docker/Dockerfile

allow spaces between `cssmin` and `cssrewrite`

fixes #619, improve sed replace regex

---

powerdnsadmin/templates/dashboard.html

Since ^ and $ for searching from start and to end is supported, let's
tell the user about it.

Add dashboard search placeholder to describe search patterns

---

powerdnsadmin/lib/utils.py

This might be handy to detect remote server problems or debugging
timeouts and the like.

Add log message after remote server request

---

powerdnsadmin/models/domain.py

This increases data inconsistency and also performance of the whole
update process: SqlAlchemy can use its own caching better with a single
transaction as it does not need to mark already fetched objects as dirty
and so re-fetch them again on later use. So after deleting a domain,
we can still use the previously fetched domain objects for the update
operations afterwards. Otherwise SqlAlchemy had to fetch each domain
object again with single SELECT statements which leads to bad
performance with many domains (>> 1000).
The introduced "do_commit" variable controls whether the database
changes are to be committed by the caller or in the called method
itself. So we can use a single transaction for the Domain.update()
method while still preserving the previous behavior for other callers. …

Perform domain sync within a single transaction

---

powerdnsadmin/templates/login.html
powerdnsadmin/templates/register.html

fix: Add favicon to fix #724
Signed-off-by: mathieu.brunot <mathieu.brunot@monogramm.io>

fix: Add favicon to fix #724

---

powerdnsadmin/__init__.py
powerdnsadmin/decorators.py
powerdnsadmin/lib/errors.py
powerdnsadmin/lib/schema.py
powerdnsadmin/routes/api.py
powerdnsadmin/swagger-spec.yaml
tests/fixtures.py
tests/integration/api/management/__init__.py
tests/integration/api/management/test_admin_user.py
tests/integration/api/management/test_user.py

Extend api with
- User management (list/get, create, update, delete)
- Account management (list/get create, update, delete)
- Assignment of users to account (list, add, remove)
Includes tests and update of swagger spec

Extend api with account and user management

---

powerdnsadmin/routes/index.py

Fix session clearing

---

.whitesource
docker/Dockerfile

Added config for WhiteSource vulnerabilities scanner
Bumped up to alpine 3.12

Alpine 3.12

---

powerdnsadmin/routes/domain.py

Sorts the account names in the dropdown menus of "New Domain" and domain "Admin" by name.

Sort accounts by name on 'New Domain' and domain 'Admin'

---

powerdnsadmin/models/history.py

Add index on table history
Fix #784

Add index on history table

---

powerdnsadmin/routes/api.py

Hello @ngoduykhanh,
Here is another PR regarding the API. With a generated client from swagger spec (is used [go-swagger](https://github.com/go-swagger/go-swagger)), the API fails because the Swagger expects a role object to be passed and not a string (likewise for the domains).
This PR enhance the endpoint to handle this case. As you notice, it is just checking the "name" field. The best would have been to use the id, but no endpoint is exposing the roles, so the user has to retrieve them on its own and hardcode it in its application. This is why I simply use the name only.
Regards

fix: API (apikeys) behaviour does not match swagger definition

---

powerdnsadmin/routes/api.py

Hello @ngoduykhanh 
Another fix to match the API spec
Regards

fix: account API output^

---

powerdnsadmin/routes/index.py

This reduces the number of graph api's calls by only using one call for all the groups, instead of a call for each group, which massively improves login time.  It also fixes the iteration through the list of groups.

Improve account creation/permission handling based on Azure oAuth group membership 

---

powerdnsadmin/routes/api.py

Attemped fix for #948
Have the API call respect the bg_domain_updates switch

respect_bg_domain_updates in routes/api

---

powerdnsadmin/routes/domain.py

limit user to only create domains for the accounts he belongs to

---

powerdnsadmin/lib/utils.py

Fix for #935 
Use .json() method if content.decode('utf-8') fails

Bug domain parse

---

powerdnsadmin/models/record.py

For some reason when some programs delete a record we get an entry returned with records: []

Fix when no records returned by API

---

powerdnsadmin/templates/admin_edit_key.html

fix for api key

---

powerdnsadmin/decorators.py
powerdnsadmin/models/setting.py
powerdnsadmin/routes/admin.py
powerdnsadmin/routes/domain.py
powerdnsadmin/templates/base.html
powerdnsadmin/templates/domain_remove.html

#951
Adds a new route, new decorator, new setting and a new template to allow users to delete their domains

allow users to remove domain

---

powerdnsadmin/models/record.py

The same solution as proposed in #670 It seems to work quite well and can easily be extended with more placeholders in the future. If this solution is accepted, some additional documentation is needed as well.

Simple [ZONE] placeholder for "advanced" templating

---

powerdnsadmin/lib/utils.py

The if condition to check for presence of  punycode is wrong.
Find will return -1 not False

fix if condition in pretty_domain_name

---

powerdnsadmin/templates/user_profile.html

It is then consistent with the email address input elements declared in
`admin_edit_account.html`, `admin_edit_user.html` and `register.html`.

user_profile tpl: set email input type attr to "email"

---

configs/docker_config.py
powerdnsadmin/models/setting.py

This allows the user to bypass the DB registartion of the oAuth variable and put it in as an environment variable.

Env oauth url

---

powerdnsadmin/models/api_key.py

See https://github.com/ngoduykhanh/PowerDNS-Admin/issues/1014.

Clarify salt re-use for API keys

---

docs/oauth.md

I recently implemented PDA auth with Keycloak and thought this documentation might be useful.

Add Keycloak documentation

---

powerdnsadmin/routes/admin.py

- Run HTML through the template engine, preventing XSS from various vectors
- Fix uncaught exception when a history entry about domain template deletion is processed
- Adapt indentation to 4 space characters per level
Considering the other issues as well, it would be good if such things could be detected before they are merged into master next time.

routes/admin.py: refactor DetailedHistory

---

.github/FUNDING.yml
README.md

As I am not actively maintaining this project anymore.

chore: remove funding and sponsor badges

---

powerdnsadmin/templates/login.html

Hi, 
This is a fix for the issue #1062

Refresh on csrf token expiration

---

powerdnsadmin/routes/index.py

Fixed LDAP Authenticator Type logging

---

README.md
powerdnsadmin/templates/base.html
powerdnsadmin/templates/emails/account_verification.html
powerdnsadmin/templates/login.html
powerdnsadmin/templates/register.html
powerdnsadmin/templates/register_otp.html
powerdnsadmin/templates/resend_confirmation_email.html

The project has recently been moved from former owner ngoduykhanh 's profile to a PowerDNS-Admin Organization. This PR fixes the repository URLs in the code to represent that change.
Again, thanks ngoduykhanh for creating PowerDNS-Admin!

Updated repository URL

---

powerdnsadmin/templates/domain.html

Render domain data table fields only as text

---

powerdnsadmin/routes/domain.py

Hello,
This PR is a fix on the #927 issue.

Log DNSSEC status change for a domain

---

powerdnsadmin/static/custom/js/custom.js

Decode domain record data and comment from HTML entity to text

---

powerdnsadmin/routes/index.py

Hello, this P.R. is a fix for issue #1167

Login requirement removal for /ping endpoint

---

powerdnsadmin/routes/admin.py
powerdnsadmin/routes/domain.py
powerdnsadmin/routes/index.py

Json load error

---

powerdnsadmin/lib/errors.py
powerdnsadmin/routes/api.py
powerdnsadmin/swagger-spec.yaml

Add health check API that also check the authoritative api.

Added health check

---

powerdnsadmin/models/user.py

fix: Active directory filter is broken

---

deploy/kubernetes/README.md
deploy/kubernetes/configmap.yml
deploy/kubernetes/deployment.yml
deploy/kubernetes/service.yml

YMLs to deploy powerdnsadmin in kubernetes cluster.

Add yml to deploy on kubernetes

---

powerdnsadmin/lib/utils.py
powerdnsadmin/models/record.py
powerdnsadmin/routes/domain.py

Idna decode

---

powerdnsadmin/routes/__init__.py
powerdnsadmin/routes/api.py

This PR replaces  #1115 as requested changes are not pushed

feat: Add /api endpoint

---

powerdnsadmin/lib/errors.py
powerdnsadmin/models/account.py
powerdnsadmin/models/setting.py
powerdnsadmin/routes/admin.py
powerdnsadmin/routes/api.py
powerdnsadmin/routes/index.py
powerdnsadmin/templates/admin_edit_account.html

#1046 
Allow hyphens and underscores in account names

feat: Allow underscores and hyphens in account name

---

powerdnsadmin/lib/utils.py

patch: Fixes #1261

---

powerdnsadmin/models/api_key.py

I added the parentheses to the `db.session.rollback` line to call the method, which will now properly roll back any changes made to the database if an error occurs.

enhancement: Small fix

---

powerdnsadmin/templates/admin_edit_key.html

hopefully this will prevent accidental administator api keys from being created

admin_edit_key: default to User role for new api keys

---

docs/wiki/database-setup/Setup-MySQL-or-MariaDB.md
docs/wiki/database-setup/Setup-PostgreSQL.md
docs/wiki/install/Running-PowerDNS-Admin-on-Centos-7.md
docs/wiki/install/Running-PowerDNS-Admin-on-Fedora-30.md

Move PostgreSQL and MySQL dependencies out to the database guides.

Fix PostgreSQL documentation

---

.github/workflows/build-and-publish.yml

Updated Docker image publish workflow to enable manual dispatch of the workflow.

Updated Docker Image Publishing Workflow

---

README.md
docs/wiki/install/Running-PowerDNS-Admin-on-Docker.md

Updated documentation to reflect the new Docker Hub home of the project's Docker images.

Docker Image Repository References Updated

---

powerdnsadmin/models/domain.py

feature: Added IDN Domain Search function as requested

---

powerdnsadmin/templates/admin_setting_authentication.html

Fixing Validation problem on LDAP form

---

powerdnsadmin/routes/index.py

Reverts PowerDNS-Admin/PowerDNS-Admin#1331

Revert "enhancement(routes/index.py): OIDC supports HTTP Scheme now"

---

powerdnsadmin/templates/applied_change_macro.html

Fixing Wrapping in History Details Modal in Dashboard

---

powerdnsadmin/routes/index.py

Might fix #1338 
Feel free to revert the changes if not

fix: Potential fix for a regex bug

---

powerdnsadmin/models/setting.py
powerdnsadmin/routes/admin.py
powerdnsadmin/services/azure.py
powerdnsadmin/services/github.py
powerdnsadmin/services/google.py
powerdnsadmin/services/oidc.py
powerdnsadmin/templates/admin_setting_authentication.html

I updated the application to include a new OAuth setting for each of the current four providers which allows the user to configure the JWKS URL to be used in the initialization of the authlib library.

Feature: Added new JWKS URL setting for each OAuth provider

---

powerdnsadmin/models/user.py

Make the OTP label the same as the site_name #1237

---

powerdnsadmin/decorators.py

Currently passing an invalid Basic auth header (random string base64 encoded) would result in an exception being raised due to a `username, password = auth_header.split()`.
I refactored the code in this decorator by checking explicitly that we are doing basic authentication then by checking the number of entries returned by the split.
I also added exception handling for invalid UTF-8 code sequences.
Tested with a fuzzer.
Tested with valid and invalid credentials.
This fixes #1447.
To make my changes easier to understand (the diff really looks messed up), please see below...

Basic Auth Exception Handling Improvement

---

configs/development.py
docker-test/Dockerfile
docker/Dockerfile
docs/wiki/database-setup/Setup-PostgreSQL.md
docs/wiki/install/Running-PowerDNS-Admin-on-Ubuntu-or-Debian.md
requirements.txt

This PR contains things to improve using PostgreSQL for PowerDNS-Admin. It contains both documentation changes as well as an addition to the requirements.txt and the docker files which are needed for that.

PostgreSQL Support Improvement

---

powerdnsadmin/routes/base.py

Currently passing an invalid Basic auth header (random string base64 encoded) would result in an exception being raised due to a username, password = auth_header.split().
Similary passing a `Digest` authentication type would result in an exception as there is no :.
Thirdly passing invalid base64 encoded UTF-8 code sequences would result in exceptions as this issue (#1424).
I added code to check explicitly that we are doing basic authentication then by checking the number of entries returned by the split.
I also added exception handling for invalid UTF-8 code sequence exceptions.
Tested with a fuzzer.
Tested with valid and invalid credentials.
This fixes #1424.

Basic Auth Exception Handling Improvement Update

---

powerdnsadmin/models/user.py

Hello,
We use an AD with nested users group for groups ADMIN, OPERATOR and USER.
Current code will find a user with `searchFilter` on the 3 groups but it will failed when looking on `memberOf` attribute, because it do not contains nested groups.
The current fix will work in this case but will do 3 requests max.
We could filter nested groups of the user but we would need to changes settings to introduces a base dn on groups.
I think its better for moment to make more requests to ldap than introduces breaking changes
What do you think about that ?

Fix LDAP user group search for nested groups

---

powerdnsadmin/decorators.py

Improve exception handling for invalid UTF-8 encoded X-API-KEY header

---

powerdnsadmin/routes/domain.py
powerdnsadmin/templates/domain_setting.html

This PR will show the current value of the Zone Type and SOA-EDIT-API settings for a zone when editing the zone.

Show the current zone type and soa-edit-api settings on the zone settings page

---

.github/workflows/build-and-publish.yml

Added support for building `ARM` and `ARM64` based Docker images.

---

powerdnsadmin/services/azure.py
powerdnsadmin/services/github.py
powerdnsadmin/services/google.py
powerdnsadmin/services/oidc.py

Updated the OAuth service providers to properly respect the new OAuth auto-configuration settings for each provider.

---

powerdnsadmin/models/record.py

The compatibility for backends that don't support comments broke the normal deletion of comments. This is fixed by limiting the compatibility to when we don't know for certain whether the backend of that zone supports comments or not. This is done by checking if the zone currently contains any comments: If it does, the backend definitely supports comments; if it doesn't, we don't know and have to assume it doesn't. The check is done by the "modified_at" attribute, because this only exists on persistent comments from pdns and not on the "fill-up" comments that PDA adds.
Luckily this also works perfectly for the deletion case, because to delete a comment it had to already exist previously.

Fix record comment removal

---

powerdnsadmin/templates/login.html

Automatically focus username field in login view: add autofocus attribute to the input element for the username

Automatically focus username field in login view

---

powerdnsadmin/routes/admin.py

Fix non rr_set events in Zone Changelog display

---

powerdnsadmin/templates/domain.html

This PR enhances domains table on dashboard. Action buttons, each in separate column consumes lot of space on smaller screens. This PR joins action buttons into single column.

Merge zone editor record action controls into single column

---

docker/Dockerfile

I applied the latest fix from @ashneilson and it appears to work well.

Added support for application to run in sub-paths while not breaking the Docker health check
