PowerDNS-Admin/PowerDNS-Admin

- README.md
- app/models.py
- create_db.py
This change populates the 'role' and 'setting' tables to their initial
states via the create_db.py script which removes a step from the initial
setup. We now also search for roles instead of expecting them to be at
certain IDs.
> Fixes issue #11.

- app/static/admin/layout2/css/custom.css
- app/templates/base.html
Change font in editable table to 'Roboto Mono' from 'Open Sans' to improve readability. Both fonts are available via the Google Fonts service.
> Change record manage table to use monospaced font.

- app/static/admin/pages/scripts/table-editable.js
This should fix the blank input field discussed in unrelated issue #28. This was the quickest place to fix it I could find and tested ok in my prod environment with a few TXT and SPF records.
@ngoduykhanh please review and test.
> Fix blank Data field when data has double-quotes in it.

- app/views.py
This fixes #62 and allows the clients real IP to show, whether PowerDNS-Admin is being accessed directly or via reverse proxy.
> Fix checkip.html route not working when not behind a proxy. Fixes #62

- app/templates/admin_history.html
- app/templates/admin_manageuser.html
- app/templates/admin_settings.html
- app/templates/dashboard.html
- app/templates/domain.html
- app/templates/domain_management.html
Direct binding only works for elements already in the DOM, delegated
binding works for all elements that match a filter even if created after
the DOM is fully loaded.
This fixes all click events that have may be created dynamically (when DataTables change pages or sort settings, etc)
> Replace direct 'click' event binding with delegated binding. Fixes #58.

- app/models.py
Currently the same TTL is used for all records in the RRset. This *could* cause entries to get deleted whenever certain circumstances are present (e.g. if you were to set `@ IN NS ns1.foo.bar` with `TTL=3600` and `@ IN NS ns2.foo.bar` with `TTL=1800`).
This change sets the TTL to be the same for all records with the same name and type.
> Use correct TTL in updates

- README.md
- config_template.py
- requirements.txt
PowerDNS-Admin uses SQLAlchemy as ORM, which supports various database backends. `MySQL-python` should not be listed as a must-have depenedency in `requirements.txt` since it needs compiling and complex setup. For testing purpose, users could use SQLite, which is a built-in function in most Python distributions.
This PR removes `MySQL-python` dependency and instructs users to try SQLite if they do not want to install MySQL / MySQL-python.
My tests show that PowerDNS-Admin works perfectly with SQLite backend.
> Users could use SQLite instead of MySQL

- app/lib/log.py
- config_template.py
If LOG_FILE config option contained invalid file, pdns admin wouldn't start.
Also, it wasn't possible to log only to stdout/stderr correctly, because
setting the log file to /dev/stdout would double the logs messages as the pdns
admin is already logging to the stderr.
> Log to file only if the file exists

- app/models.py
Set password to '*' for users created by the create_user method. Should cause an invalid password hash for non local users added to the database
> Fix issue #133. Store hash as '*' for external users

- app/templates/admin_history.html
- app/templates/base.html
- app/templates/dashboard.html
Fetch UTC date/time directly from DB and display it could be confused user.
It would be better to format it using user's browser timezone before display it to the user.
> Format history date/time before display using browser timezone

- app/views.py
Please observe this (very small) change. It is needed to friendly fail with a message when a non-numeric otp was inserted.
Thanks!
Regards René Dekkers
> Fail when non-numeric otp token was inserted

- app/models.py
- app/templates/domain_add.html
- app/templates/domain_management.html
The options used for `SOA-EDIT-API` in PowerDNS-Admin, are wrong and don't work as expected. They are meant for `SOA-EDIT`, which is something else entirely.
This PR replaces the bad option-list with a new good one and takes care to only pass good values for SOA-EDIT-API to the powerdns API.
Solves #262 - Tested on my own setup.
> Fix SOA-EDIT-API options

- app/views.py
The result from the form is never an int but rather a string of digits, so that's what we should be checking for.
This fixes OTP validation
> Fix OTP validation

- app/templates/admin_manageuser.html
- app/views.py
Disable the admin toggle and delete operations from the current user, to avoid accidents.
> Restrict certain admin changes on the current user

- app/models.py
- app/templates/admin_editaccount.html
- app/templates/admin_manageaccount.html
- app/templates/base.html
- app/templates/dashboard.html
- app/templates/dashboard_domain.html
- app/templates/domain_add.html
- app/templates/domain_management.html
- app/views.py
This adds initial support for accounts a concept meant to signify a customer, a department or any other entity that somehow owns or manages one or more domains.
Meant to solve #267 but using an approach that allows for greater control and easier management.
The purpose is to be able to assign an account to any number of domains, making it easy to track who owns or manages a domain, significantly improving manageability in setups with a large number of domains.
An account consists of a mandatory, unique `name` and optional `description`, `contact` name and `mail` address. The account `name` is stripped of spaces and symbols, and lower cased before getting stored in the database and in PowerDNS, to help ensure some type of predictability and uniqueness in the database.
The term *account* is …
> Initial support for Accounts

- app/__init__.py
To avoid problems with inactive DB connections, SQLAlchemy provides a `pool_pre_ping` option, that is described in more detail here:
http://docs.sqlalchemy.org/en/latest/core/pooling.html#disconnect-handling-pessimistic
In Flask environments, it's enabled by subclassing SQLAlchemy, which is what I've done here.
This fixes errors like:
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away') which results in an Error 500 in the UI.
> Enable pool_pre_ping in DB connection

- .gitignore
Just as we ignore special files/folders for the Eclipse and PyCharm IDEs, please ignore .vscode used by Visual Studio Code.
> Add Visual Studio Code settings folder to .gitignore

- app/models.py
- app/templates/admin_settings.html
- app/views.py
- init_data.py
Moves setting definitions into code (rather than database).
Aims to fix issues such as #175 and #194 .
For a setting to be useful, the code has to be able to make sense of it anyway. For this reason it makes sense, that the available settings are defined within the code, rather than in the database, where a missing row has previously caused problems. Instead, settings are now written to the database, when they are changed.
So instead of relying on the database initialization process to create all available settings for us in the database, the supported settings and their defaults are now in a `defaults` dict in the Setting class. With this in place, we can stop populating the `setting` table as a part of database initialization and it will be much easier to support new settings in the …
> Improve setting handling

- app/models.py
- app/templates/domain.html
- app/views.py
Add a setting to allow easily toggle "quick editing" of records on/off through the settings UI.
***Note***: This PR makes use of the improved settings infrastructure proposed in #287, so by necessity includes the changes from that PR here, too. This may require me to do some rework if #287 is merged, which I'm happy to do.
Aims to fix #288
> Add allow quick edit setting

- docker/PowerDNS-Admin/Dockerfile
- docker/PowerDNS-Admin/entrypoint.sh
Adds a healthcheck on container start to ensure the MySQL DB is ready.
This isn't an issue in the docker-compose because of the way `depends_on` works in v2.1, but when upgrading to newer versions (or orchestrating user a different tool), this becomes an issue when deploying DB and app simultaneously.
> Wait for MySQL to be ready before initialising/upgrading database when starting container

- app/models.py
PowerDNS 3.x API does not support setting or getting account info.
This patch lets PowerDNS 3.x users use the rest of the interface without problems.
Account stuff still does not work.
A message is logged in debug mode, to help with troubleshooting on newer versions
of PowerDNS.
> Tolerate pdns 3.x API deficiencies

- app/models.py
Resolves #324 
As mentioned in https://github.com/ngoduykhanh/PowerDNS-Admin/issues/324#issuecomment-411262030, there is an explicit decode to utf-8 on the password [when creating a user](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/c6bb58cfdafb797b015c0de50330467855382cf8/app/models.py#L324), but not on updating a profile. This seems to cause issues with PostgreSQL, as the string it is trying to insert into the `password` column is suddenly twice the length. This PR fixes the issue for Postgres.
Note that I am currently unable to test this in MySQL, so someone else has to do that. :)
> Decode passwords as UTF-8 on profile updates as well

- app/templates/user_profile.html
When toggling Two Factor Authentication, it often takes a few tries to get it to work.
The toggle function ends up reloading the page in two different places, effectively creating a race condition.
This fixes that problem
> Fix double refresh when activating 2FA

- app/lib/utils.py
- config_template.py
Fixes ngoduykhanh/PowerDNS-Admin#322
Adds new optional config setting `SAML_IDP_SSO_BINDING` for which [SAML binding format](https://en.wikipedia.org/wiki/SAML_2.0#SAML_2.0_Bindings) to use. If not specified, use library default.
> Allow specifying SAML2 SSO binding format.

- app/models.py
Often, you need a CNAME to point to the base domain name, but with a lot of domains and a lot of records, it can become tedious and even error prone to have to type out the domain name in full.
This PR enables the use of the shorthand `@` (or blank) for `CNAME` records, so that if a CNAME record is specified to point to '@' or '', it's replaced with the base domain name.
> Allow CNAMEs to point to '@'

- app/static/custom/css/custom.css
- app/templates/base.html
Making it a little more evident, that the profile- and logout buttons exist in that dropdown.
Aiming to fix #332 
Colors are taking the elsewhere in the theme and - to me - seems to match.
> Change user-dropdown button colors

- app/models.py
- app/views.py
This patch is meant to have a session timeout shorter than the default flask_login one.
I manually added a new setting called session_timeout in the setting table, with a default value of 10 minutes:
insert into setting(name,value, view) values('session_timeout', 10, 'basic');
I didn't quite understand the way new settings were added in the database depending on the version of alembic (files in migrations/versions), It may be necessary to complement this patch with the proper migration file.
> Setting a session lifetime

- app/models.py
This patch is to check whether a user is in LDAP_ADMIN_GROUP or LDAP_OPERATOR_GROUP, or in a group that recursively makes the user a member of those groups.
It allows managing users in the Active Directory by setting them in groups corresponding to teams, and then adding the teams in the proper group to give them administrative or operator access.
> Recursively find user's ActiveDirectory groups

- app/templates/admin_edituser.html
Just a small typo in the title of the Edit User page
> Fix typo Use -> User

- app/models.py
- app/static/custom/js/custom.js
- app/templates/domain.html
- app/templates/template_edit.html
- app/views.py
- requirements.txt
Adds a new setting to define the options in the TTL dropdown when
editing a record. The setting is a comma separated string with the
valid options.
Fixes #362
> Add ttl_options setting

- app/models.py
When checking a DomainSetting against None with "==", an exception is thrown. See [here](https://github.com/ngoduykhanh/PowerDNS-Admin/pull/455/files#r255691535) for the explanation.
> fix equality check for DomainSetting when "other" is None

- app/lib/utils.py
- app/models.py
- app/views.py
Besides accepting IPv6 addresses in general, this implements two items from https://help.dyn.com/remote-access-api/perform-update/ regarding the **myip** parameter:
1. Use commas to separate multiple IP addresses in the myip field.
2. If this parameter is not specified, the best IP address the server can determine will be used (some proxy configurations pass the IP in a header, and that is detected by the server). If the IP address passed to the system is not properly formed, it will be ignored and the system’s best guess will be used.
> dyndns: accept and validate both A and AAAA records; default to client address

- app/lib/utils.py
- app/views.py
- config_template.py
- configs/development.py
- configs/test.py
Hi
I tried to integrate this with AzureAD and hit a few issues, 
I've made some changes to make this flow work better, let me know what you think
- Make SAML_WANT_MESSAGE_SIGNED configurable, AzureAD signs the assertion but wouldn't sign the message
- Add support for a name attribute, i.e. 'Tim Jacomb' using `SAML_ATTRIBUTE_NAME`, which will be mapped into the given and surname fields, AzureAD only has displayname
- Add support for group based admin `SAML_ATTRIBUTE_GROUP` and `SAML_GROUP_ADMIN_NAME`
- Add support for group based accounts `SAML_GROUP_TO_ACCOUNT_MAPPING`
- Don't fail if cert and key aren't present
I've updated the config_template.py
Didn't see anywhere where there was tests for this but let me know if you need me to update anywhere
> Improve SAML support

- app/models.py
The LDAP search filter used for group queries needs to be escaped so that group names with special characters will not break the search filter in queries. e.g. a query for a group with a Common Name with parens will return 'Bad search filter' and break authentication.
> escape special chars when creating group filter.

- app/models.py
- app/views.py
When you want to display records for a domain, it will make 4 SQL requests for each records entry, to retrieve Settings fields which are not used at all in the domain page. This results in a really slow processing time, in our case for a zone with 4000 records, it will make 16000 queries.
This PR will create a new class just for storing records entries, which is sufficient for the domain page template.
Before this PR, the rendering of our 4000 records took 7 minutes, and now it only takes 4 seconds.
> Records entries must not make database requests for domain listing page

- app/models.py
When calling the API API-Key and PlainText Password got logged.
Probably left in by mistake.
> Removed API-Key and PlanePassword logging

- docker/Production/Dockerfile
- docker/Production/config_docker.py
- docker/Production/entrypoint.sh
The current installation method is rather dirty and involves a lot of 3rd party tools. I wrote a Dockerfile for a clean installation of PowerDNS-Admin so it can be used in production with a clean environment. 
Usage for reference:
Create a env file `pdnsadmin-env`:
```
SECRET_KEY=your-very-secret-key
TIMEOUT=10
LOG_LEVEL=DEBUG
LOG_FILE=logfile.log
SALT=$2b$12$somerandomsalt
SQLALCHEMY_TRACK_MODIFICATIONS=True
SQLALCHEMY_DATABASE_URI=postgres://user:password@your.server.address:5432/database-name
```
Then run the prebuilt docker image:
```shell
docker run -p 9191:80 --env-file pdnsadmin-env jamesits/powerdns-admin:latest
```
Visit `http://localhost:9191` and you are ready to go.
> a Dockerfile for production run

- app/errors.py
Hello,
Presently the API returns non-standard complaint HTTP response codes. This causes reverse proxies such as Apache 2.4 to drop the responses:
[Thu Jun 27 18:23:12.684170 2019] [proxy_http:error] [pid 11733] (70014)End of file found: [client 216.19.183.221:53670] AH01102: error reading status line from remote server 127.0.0.1:8000
[Thu Jun 27 18:23:12.684611 2019] [proxy:error] [pid 11733] [client x.x.x.x:53670] AH00898: Error reading from remote server returned by /powerdns-admin/api/v1/pdnsadmin/apikeys
I'm proposing the following changes to the HTTP response codes, as I cannot see them being used anywhere else I don't think this should break any workflows.
> Standard compliant HTTP Response codes

- app/assets.py
- package.json
Natural sort was originally introduced in #72, but became broken at some point.
This PR fixes #551 and #486.
> Add natural sort library

- powerdnsadmin/routes/index.py
- powerdnsadmin/services/saml.py
- Variable references inside SAML class were fixed
- Function signatures inside SAML class were fixed
- Redirect URL for /saml/login path was modified (saml_authorized -> index.saml_authorized)
Current status is that SAML metadata can be generated under /saml/metadata and communication to SAML iDP is working
Problems remaining:
- SAML Response doesn't contain any attributes (There is no AttributeStatement on the Response). Probably it is problem on iDP side. I'll need to take other SAML iDP.
- Background thread in retrieve_idp_data() cannot be spawned, this part is currently commented out, old code needs to be revisited. Will to try to resolve it soon.
> Most of SAML integration fixed

- powerdnsadmin/lib/utils.py
- powerdnsadmin/models/domain.py
- powerdnsadmin/models/record.py
- powerdnsadmin/routes/admin.py
- powerdnsadmin/routes/domain.py
- powerdnsadmin/routes/index.py
- powerdnsadmin/static/custom/js/custom.js
- powerdnsadmin/templates/dashboard.html
- powerdnsadmin/templates/domain.html
- powerdnsadmin/templates/template_edit.html
- yarn.lock
Change the way of submitting record changes from PDA to PDNS API. Create diffs (new records, deleted records) and submit to PDNS instead of sending all domain records data.
This will help:
- Send fewer data to PDNS API
- Keep the Record ID unchanged in PDNS database if it is not really updated. #526 
- Better displaying of "detail" in History feature. #354 #479 #590
TODO/Improvement:
> Adjustment in domain's record applying

- configs/development.py
- powerdnsadmin/lib/certutil.py
- powerdnsadmin/services/saml.py
Problems resolved:
- Method create_self_signed_cert() was invoked nowhere. This puts parameter "SAML_SIGN_REQUEST" description in configs/development.py as incorrect
- Method create_self_signed_cert() was returning error while trying to write out certificate and private key. File handler was opened for writing out TEXT instead of BINARY data
Enhancements:
- Two new parameters are introduced SAML_CERT_FILE and SAML_KEY_FILE. User can now explicitly define own certificate and key file anywhere on file-system.
- If parameters mentioned in previous bullet aren't explicitly defined, in PowerDNS-Admin root directory self-signed certificate will be created.
- Certificates will be used or generated in any case, because in saml.py there are explicit parameters defined which require certificate/key …
> SAML certificate fix and enhancement

- configs/development.py
- powerdnsadmin/services/saml.py
Enhancements:
- Added support for SAML Requested Attributes through "SAML_SP_REQUESTED_ATTRIBUTES" parameter
- Minor change for more robust check when creating self-signed certificates (prevents potential unwanted behaviour)
> Support for SAML metadata Requested Attributes

- powerdnsadmin/models/setting.py
- powerdnsadmin/routes/admin.py
- powerdnsadmin/routes/index.py
- powerdnsadmin/templates/admin_setting_authentication.html
This minor change adds Group ID to Role mappings for the Azure OAuth authenticator.
As with LDAP, groups are defined for Admin, Operator and User which are then (if the feature is enabled) mapped to role at login time.
There is also some additional on-screen help when configuring the Azure authentication; and some debug logs added to help track down Azure authentication issues (when your App is misconfigured in Azure you may not get all the attributes you expect passed through)
> Azure OAuth - add Group mappings to Roles

- powerdnsadmin/__init__.py
By setting the environment variable PDNS_ADMIN_LOG_LEVEL to a Python
support log level, PowerDNS-Admin will use that log level.
If the environment variable is missing, `WARNING` will be used what is the current default.
I like to set the log level to info (which was the default in earlier versions) and with this change this is possible again.
> Introduce PDNS_ADMIN_LOG_LEVEL to change the log level

- powerdnsadmin/lib/utils.py
- powerdnsadmin/models/domain.py
- powerdnsadmin/models/record.py
- powerdnsadmin/models/server.py
- powerdnsadmin/models/setting.py
- powerdnsadmin/routes/admin.py
- powerdnsadmin/routes/api.py
The new setting 'verify_ssl_connections' tells the requests library to
verify secured outgoing HTTP connections.
Usually verifying is desired and helps to reveal configuration
problems. It also disables an ugly warning when HTTPS connections
are made without verification.
Most people probably connect to the PowerDNS API via plain HTTP connections anyway. But for those few who connect via HTTPS, SSL verification should be enabled unless they explicitly disable it.
> Add new setting to verify outgoing SSL connections

- powerdnsadmin/services/github.py
- powerdnsadmin/services/oidc.py
Seems like typos during code refactoring.
I didn't test the changes but I think now it's better than before with setting wrong token names in the session.
> Fix token name in session for OIDC and GitHub authentication

- powerdnsadmin/services/azure.py
This adds the missing items from the azure auth support that were causing the head branch code to fail to log in via AAD.
Tested on our installation with head as at 28/02/2020.
> Corrections to Azure auth service definition after refactor

- powerdnsadmin/lib/helper.py
I recently opened this issue: https://github.com/ngoduykhanh/PowerDNS-Admin/issues/666
I've found the issue, the method of flask "request" in order to call de pdns api with the parameter is request.full_path rather than request.path in the file helper.py.
I hope this pull request be useful.
Regards.
> Correct request method

- README.md
- configs/docker_config.py
Can you add this request, it enables support for docker secrets. This gives a more secure option of storing credentials and pass them to containers.
> Add docker secrets support

- docker/Dockerfile
- requirements.txt
In this PR I updated the Dockerfile from Alpine 3.10 to 3.11. Additionally pip was updated to avoid the error message of the outdated pip version. To set the correct local timezone (environment variable "TZ" must be set) tzdata was added.
Due to the bug (https://github.com/benoitc/gunicorn/issues/2091) I also had to update gunicorn. 
Please test before merging.
> Update Alpine 3.10 -> 3.11; update pip, tzdata, gunicorn

- powerdnsadmin/templates/dashboard.html
As the URL here is contructed from Flask's "url_for" which already
takes the script root into account, we do not need to add it here
explicitly. This would result in a duplicate script root otherwise.
> Remove $SCRIPT_ROOT from 'admin.create_template_from_zone' URL

- powerdnsadmin/routes/admin.py
- powerdnsadmin/routes/index.py
- powerdnsadmin/templates/login.html
Currently you can't disable the local db auth if you are using an oauth provider (for example Microsoft Azure).
This adjust the validation to require at least one enabled authentication provider, and ends up being a little noise for a commit
> Support only having one auth method enabled 

- README.md
- configs/docker_config.py
- docker/Dockerfile
- docker/entrypoint.sh
This allows for easy setup with no extra configuration.
Also update docs to reflect the new and easy way to run PowerDNS-Admin.
Signed-off-by: Felix Kaechele <felix@kaechele.ca>
> Use sqlite by default in docker

- powerdnsadmin/routes/index.py
This fixes a bug where if the tenant does not have any licenses (in particular sharepoint online) the get request for preferredName fails due to missing license.
The other fixes a minor name error, where 'email' is used instead of 'mail'
> Azure oauth fixes

- powerdnsadmin/models/setting.py
- powerdnsadmin/routes/admin.py
- powerdnsadmin/routes/index.py
- powerdnsadmin/templates/admin_setting_authentication.html
As discussed on issue #713 and later on pull request #714, I have created custom claims for oidc for changing easily the translation from oidc to the user database.
> oidc custom claims

- powerdnsadmin/models/record.py
- powerdnsadmin/routes/domain.py
When comparing submitted with current, the system can sometimes incorrectly things an rrset has changed when in fact it is just the members in a different order.  This can potentially do major damage if a change fails (such as when accidentally adding an A record when a CNAME already exists), as the delete will take place but the re-create fail, resulting in the accidental deletion of an entire rrset unrelated to the change being attempted,
This change adds a sort of the rrset members for both retrieved (get_rrset) and submitted (merge_rrset), sorting the record+comment pair by the record content.  Note that blank comments have to be added if for any reason the comment array is not the same length as the record array for this to work.
Also this change will default comment to blank entry …
> Sort rrset members by content before comparison to ensure correct compare

- powerdnsadmin/models/record.py
As per #676 when submitting changes to a backends that doesn't support comments the api call will fail. This is really only an issue with the [LMDB backend](https://doc.powerdns.com/authoritative/backends/lmdb.html) as most of the other traditional backends support comments. 
I propose removing the comments field from the api request if the comment is blank. This should allow the request to succeed if the backend supports it and gives a clear error if it fails. 
I refrained from creating a setting to remove comments as it would silently delete them without notifying the user. Full disclosure I haven't tested this on other backends. This was a quick fix, so suggestions are welcome.
> Remove blank comments from rrsets before sending for compatibility

- configs/development.py
- configs/docker_config.py
- powerdnsadmin/lib/utils.py
- powerdnsadmin/models/user.py
- powerdnsadmin/routes/base.py
- powerdnsadmin/routes/index.py
- If new `REMOTE_USER_ENABLED` config setting is set to `True`, a username can be provided through a `REMOTE_USER` environment variable, which will be used to login into PowerDNS as a "trusted user".
- A new `LOCAL` user will be created as well and used in subsequent requests. This mimics the existing _Basic Authentication_ flow.
- Allows easy integration with existing SSO providers, such as [CAS](https://github.com/apereo/mod_auth_cas).
New available settings (values shown below are examples, not defaults):
```py
REMOTE_USER_ENABLED=True
REMOTE_USER_LOGOUT_URL=https://my.sso.com/cas/logout
REMOTE_USER_COOKIES=['MOD_AUTH_CAS', 'MOD_AUTH_CAS_S']
```
This is my first PR here and I'm not really familiar with the overarching architecture of PDNS, so there might be a better/different approach …
> Support authenticating using REMOTE_USER environment variable

- powerdnsadmin/templates/domain.html
As mentions in https://github.com/ngoduykhanh/PowerDNS-Admin/issues/755 issue, this pull request created in order to solve the problem of defaulted 1 hour of TTL.
> Changed default TTL

- powerdnsadmin/routes/domain.py
Hi, 
fixes a bug where PowerDNS-Admin will fail with 500 when
- zone is ipv6
- pretty ptr is enabled
- zone contains wildcards
> do not fail with wildcard PTRs

- powerdnsadmin/routes/admin.py
- powerdnsadmin/templates/admin_edit_key.html
- powerdnsadmin/templates/admin_manage_keys.html
- powerdnsadmin/templates/base.html
I recently came across the feature of API Keys. The feature was pretty hidden, under-documented, and unintuitive.
I think it will be great to add this API key feature to the UI so the admin can create/delete/update API Keys easily from the portal and not through curl or postman.
Currently, this feature is implemented exactly like the API, where only admins can create keys.
As I mention in issue #803 I think we can extend this feature of API keys even more and make it more accessible and more easily used.
> Add API Key to the UI

- powerdnsadmin/templates/base.html
After #738 gravatar broke in offline because of incorrect templating at:
https://github.com/ngoduykhanh/PowerDNS-Admin/blob/4e63f8380bd6daa3fe5a651ee6d600be64f6dfd8/powerdnsadmin/templates/base.html#L32
> Fix gravatar offline mode

- powerdnsadmin/models/setting.py
- powerdnsadmin/models/user.py
- powerdnsadmin/routes/admin.py
- powerdnsadmin/routes/index.py
- powerdnsadmin/templates/admin_setting_authentication.html
This PR adds the following:
1. Update User details on every login.
2. If `oidc_oauth_account_name_property` and `oidc_oauth_account_description_property` are set, automatically create or update an Account during login, and add the User to it.
3. Allows setting of `oidc_oauth_logout_url` to automatically redirect the user to an IdP logout URL, for single logoff .
We store all our user information in an IdP, and can match a User to an Account using just the information returned from the userinfo response. For instance:
```json
{
"given_name": "Mary",
"family_name": "Lamb",
...
"my-customer-id": "customer123",
"my-customer-name": "Customer 123"
}
```
Setting `oidc_oauth_account_name_property` and `oidc_oauth_account_description_property` to 'my-customer-id' and 'my-customer-name' …
> OIDC User and Account management during login

- docker/Dockerfile
- docker/entrypoint.sh
- avoid running gunicorn as root user
- use setcap to allow gunicorn starting with a privileged port
- write permission only on /app/configs folder
- su command removed from entrypoint.sh, because it runs as pda user
- tested with `docker build -f docker/Dockerfile -t powerdns-admin:master .`
> USER instruction enabled in Dockerfile

- powerdnsadmin/models/account.py
- powerdnsadmin/models/domain.py
- update_accounts.py
Allow syncing of all known accounts from PowerDNS, in the same way that Domain().update() does for domains.
We use OIDC as our login method (see #800 for more details). Using the new method in this PR we can pre-create all known Accounts for all domains, so that when the user logs in, he is automatically matched to the right Account and can manage his domains immediately. We can also now sync all Accounts and Domains in one job:
```python
import sys
import logging
from powerdnsadmin import create_app
from powerdnsadmin.models.account import Account
from powerdnsadmin.models.domain import Domain
from powerdnsadmin.models.setting import Setting
app = create_app()
app.logger.setLevel(logging.INFO)
with app.app_context():
status = Setting().get('bg_domain_updates')
if not status: …
```
> Implement account update method

- powerdnsadmin/templates/base.html
Using PowerDNS-Admin on an iPad with Safari can cause incorrect identification of some record data as a telephone number. When submitted, the record with the incorrectly identified data causes an error because of the additional markup present on the submitted data. This was noted in particular with the SOA record. 
The proposed change is to add the Safari meta tag to disable format detection:
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html#//apple_ref/doc/uid/TP40008193-SW5
> Avoid Safari telephone number detection

- powerdnsadmin/decorators.py
- powerdnsadmin/routes/api.py
As described in  #844, please find the tweaks I made to allow User api keys to use Terraform Powerdns Provider to create records. (zone creation will obviously not work with user api key.  You have to provide admin Key for that).
Please review this proposal (not sure about creating security issues by opening /servers and /servers/<server_id> (GET only) to non admin users .. (but still registered api key)...
Best Regards,
> Tweaks to allow  user apikey usage with powerdns terraform provider

- powerdnsadmin/models/user.py
- powerdnsadmin/routes/api.py
Fixes #859 
This test ensure the role is applied if it is defined when we create a user through the API.
Thank you @ngoduykhanh
> fix: User role was not assigned upon creation

- powerdnsadmin/routes/api.py
Closes #857
As you can see in the [official PDNS API doc](https://doc.powerdns.com/authoritative/http-api/zone.html), all requests on the /zone/<zone_id> endpoint returns either 204 "No content" or a 200 "OK" result. Your code tries to extract the rrset data from these blank answers causing the failure.
Still this patch is somehow wrong because I must totally remove the first test anyway as there is no POST method on this endpoint as the doc states now. It may be a breaking change on the last versions of PDNS (I run on 4.3 now) and as you configure a version number in PDNSA you may want to test the configured version to change the behavior.
Let me know, I can slightly change the code.
> fix: Follow PDNS Api return format

- powerdnsadmin/routes/api.py
Hello @ngoduykhanh 
I tried to make a go client from your swagger spec with go-swagger tool. From the description, all returned data from the API is application/json, but headers were not set and defaulted to text/html.
The client raise an error because it expects json. I updated all json.dumps() to use Flask's jsonify() which correctly sets headers.
If there is any particular reason let me know.
Regards
> fix: user jsonify to set response headers to json

- powerdnsadmin/decorators.py
- powerdnsadmin/routes/api.py
#847 #848 
Hello @ngoduykhanh 
I have written 2 ansible modules to drive your API: one for managing accounts, one for managing users. I want to show on the output the domains that are associated to the account. 
I create domains through Terraform, so I need to browse the sync_domain endpoint to refresh existing domains so the account is populated with associated domains.
The problem is that your API is split in two parts: 
* The management endpoints in /pdnsadmin is accessed with basic auth
* The PowerDNS proxied endpoint is accessed with an API Key
* The sync_domain endpoint is surprisingly also protected by the API Key
To keep my module consistent (the ones to manage PDNS Admin) I use a traditional user/password setup to browse PDNS Admin API with basic auth. We are also supposed to do …
> feat: Allow sync domain with basic auth

- powerdnsadmin/routes/api.py
This patch enforces zone filtering on /servers/localhost/zones endpoint for API Keys with User role, thus limiting listing to allowed zones. It returns PDNS content untouched.
Response to #856
> feat: limit zone list for users on servers endpoint

- powerdnsadmin/routes/api.py
- powerdnsadmin/swagger-spec.yaml
@ngoduykhanh 
Hello,
The swagger specs defines a pdnsadmin/apikeys/<key_id> endpoint that was not implemented (it falls back on the /apikeys which return a list of keys instead of a specific key).
Added here
> feat: Implement apikeys/<id> endpoint from swagger spec.

- README.md
- powerdnsadmin/__init__.py
- powerdnsadmin/lib/utils.py
- powerdnsadmin/models/record.py
- powerdnsadmin/routes/api.py
- powerdnsadmin/routes/domain.py
- powerdnsadmin/templates/dashboard_domain.html
- powerdnsadmin/templates/domain.html
- powerdnsadmin/templates/domain_setting.html
Add support for punycode (IDN) domains and records.
This is built upon the original [PR#597](https://github.com/ngoduykhanh/PowerDNS-Admin/pull/597).
- domains and records now always show up pretty
- CNAME records can be pointed at IDN names
- IDN shows up correctly even when only the TLD is an IDN
- Search is still not working (will require smart adjustments that probably go deeper into how this works for now)
- Display of both idn encoded and non-idn-encoded values does not seem to be of much use for now (maybe as a tool-tip ?)
- JS modals that display domain/record names still do not show the pretty version yet
> Add punycode (IDN) support

- powerdnsadmin/lib/errors.py
- powerdnsadmin/lib/schema.py
- powerdnsadmin/models/user.py
- powerdnsadmin/routes/api.py
- powerdnsadmin/swagger-spec.yaml
- swagger-specv2.yaml
@ngoduykhanh 
Hello
This PR include multiple changes:
- it changes the output of the user endpoint, so it's in line with the last changes to apikeys and accounts
- it changes the user/account link endpoints to a more logical path accounts/<account_id>/users/<user_id> (the old pattern is not removed but swagger definition has been updated to match the new one)
- it adds account information to users (if you get one, not the list)
- it fixes a bug I introduced in #874
- it introduce a cleaner way to output the results (using lima library to not output json object as a collection instead of tricking jsonify by giving the generated list first item as argument)
~~I need some help because I'm not comfortable with SQLAlchemy. I'd like to add an account property to the User class. I have tried to …
> upd: improve user api

- powerdnsadmin/models/domain.py
This fixes a bug I introduced, the history records for a domain are now deleted before the domain is deleted.
This will resolve issue #915
> Bugfix: delete history records when a domain is deleted

- README.md
This project provides a default SECRET_KEY for signing session-cookies:
https://flask.palletsprojects.com/en/1.1.x/config/#SECRET_KEY
By using the default SECRET_KEY, everyone will be able to create valid session-cookies.
So users should be aware that it is very important to set a custom SECRET_KEY.
It would be even better if PowerDNS-Admin would refuse to start if the default SECRET_KEY is used.
> Emphasize importance of using a custom SECRET_KEY

- powerdnsadmin/models/record.py
Proposed fix for backends that do not support comments, such as LMDB.  See ngoduykhanh/PowerDNS-Admin#919.
> Delete blank comments.  Fix for ngoduykhanh/PowerDNS-Admin#919

- powerdnsadmin/routes/admin.py
This sets account_user_ids to empty list, preventing jinja exception
```
def edit_account(account_name=None):
users = User.query.all()
if request.method == 'GET':
if account_name is None:
return render_template('admin_edit_account.html',
users=users,
account_user_ids=[],
create=1)
```
That should fix #937
> setting account_user_ids to empty list on GET /account/edit

- docker/Dockerfile.BackgroundJob
- powerdnsadmin/lib/utils.py
- update_accounts.py
- update_zones.py
#939 
This changes the files "update_zones.py" and "update_accounts.py" slightly, changing the error message to lower priority. It also moves them to the powerdnsadmin directory inside the docker image.
A new Dockerfile "Dockerfile.BackgroundJob" is created. This docker image differs from the stock one provided by including the s6-overlay https://github.com/just-containers/s6-overlay 
That way, a cron instance can be started next to PowerDNS-Admin.
Using that, the Docker Image will automatically update Zones and Accounts every 5 minutes if the "bg_domain_updates" setting is enabled.
TLDR:
Have Dockerfile with background jobs
> Add background jobs to docker

- powerdnsadmin/routes/dashboard.py
The background domain sync can be take alot of time when theres alot of domains, this is why there is a setting to sync the domain manually instead of syncing it in the background for each http request.
Now the button and the API is open for every authenticated user.
This create a problem - we know the request can take alot of time but we still give regular users the power to initiate such process. This API can be easily abusable by malicious users and can cause performance degradation or even denial of service.
This pull request limit the API (and showing the button) to only users with operator role or higher, which we know we can probably truest.
> bg_domain button for operators and higher

- powerdnsadmin/lib/schema.py
Retrieving an account from the API is broken, it just fails, because added accounts key is a list, requiring many=True option
> fix: Accounts API is broken

- docker/Dockerfile
The builder image does not need to cleanup itself, 
the whole purpose of it is to be dropped after the final artifacts are copied out.
> Remove unnecessary build step

- requirements.txt
We can't deploy anymore because the 2.2.2 version have dependencies that are no longer available in pip. Using this version (the author just removed the obsolete library usage to create the 3.0.0 version) let us install PDNSA.
> fix: jsmin 2.2.2 no longer available. Use 3.0.0

- powerdnsadmin/routes/admin.py
- powerdnsadmin/templates/admin_setting_authentication.html
This correctly saves the value, but I have not been able to validate
that it actually properly calls the IDP logout URL with the desired effect.
This is due to other issues with the OIDC feature and my IDP.
> fix: actually store OIDC logout URL

- configs/development.py
- configs/test.py
- powerdnsadmin/default_config.py
SQLAlchemy database URLs follow RFC-1738, so parameters like username
and password need to be encoded accordingly.
https://docs.sqlalchemy.org/en/13/core/engines.html#database-urls
---
See https://github.com/ngoduykhanh/PowerDNS-Admin/issues/1036.
> default config: add exemplary URL encoding step for SQLA DB URL params

- powerdnsadmin/models/api_key.py
- powerdnsadmin/routes/api.py
The implementation of `random.choice()` uses the Mersenne Twister, the
output of which is predictable by observing previous output, and is as
such unsuitable for security-sensitive applications. A cryptographically
secure pseudorandom number generator - which the `secrets` module relies
on - should be used instead in those instances.
> Use secrets module for generating new API keys and passwords

- powerdnsadmin/models/user.py
The order of account names returned by `User.get_accounts()` affects the order account names are displyed in on /domain/add if the current user neither has the Administrator role nor the Operator role and the `allow_user_create_domain` setting is enabled at the same time.
If the current user does have the Administrator or Operator role, `routes.domain.add()` already returns accounts ordered by name, so this change makes it consistent.
> models.user: get_accounts(): order by name

- powerdnsadmin/swagger-spec.yaml
Hello,
It may be a detail but i couldn't generate a client that works with the old definition. It waited for a list of list of dicts because the referenced object is already a list.
Regards
> fix: Error in the swagger AccountSummary definition

- powerdnsadmin/templates/domain.html
While working with PDA I had often the use to get from the Domain Records to the Admin page of it, to for example assign an account to it.
Therefore it would be nice to have a button for it to get to there.
> Add button for admin page in single Domain view

- requirements.txt
Fix for issue #1125.
The latest version of itsdangerous (2.1.0) is not compatible with Flask 1.x, therefore the previous version (2.0.1) must be used until the app gets upgraded to Flask 2.x
> Pinned compatible itsdangerous version to requirements

- requirements.txt
Fix for issue #1146
The importError originates from the fact that [Jinja2 version 3.1.0](https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0) released on 2022-03-24 requires that "Markup and escape should be imported from MarkupSafe" .
> jinja-dependency-fix

- requirements.txt
As mentioned in issue #1150, werkzeug was updated to [3.1.0 ](https://werkzeug.palletsprojects.com/en/2.1.x/changes/#version-2-1-0), dropping support for Python 3.6.
> Fixed werkzeug dependency

- powerdnsadmin/models/domain.py
- powerdnsadmin/models/record.py
- powerdnsadmin/routes/api.py
Improvment for  #1107
PowerDNS Admin can be configure to interact with another PowerDNS Admin instance's API. In such setup, content can't be managed because PowerDNS makes REST calls without setting a Content-Type header. PowerDNS never complains about this, but PowerDNS Admin needs content type.
This PR adds the Content-Type wherever it may be needed.
> fix: Set Content-Type on backend API calls

- powerdnsadmin/decorators.py
The common procedure for HTTP Basic Auth is that a client does /not/
immediately send out credentials via an 'Authorization'-header, but to
wait until the server tells the client to do so - which the server
indicates via the 'WWW-Authenticate'-header.
PowerDNS-Admin (and flask in general), though, abort the whole
communication if no Authorization header was found in the initial
request - resulting in '200 "badauth"'.
While this might work for /some/ HTTP clients - which right away add an
Authorization header crafted from provided credentials (via args or
extracted from given URL), this is /not/ standard and /not/ common.
Hence add the 'WWW-Authenticate'-header for every unauthenticated call
checking for dyndns authorisation.
Note, though, this changes the status code from 200 to 401 in …
> dyndns: Respond with HTTP header 'WWW-Authenticate' to unauthed requests

- powerdnsadmin/routes/index.py
The onelogin package is not part of all saml packages for whatever
reason (e.g. Debian) and not easily installable from pypi (requires
CC toolchain).
As the onelogin functionality is already guarded by whether
SAML_ENABLED is set in other places (services/saml.py), also do so
in routes/index.py.
> routes/index.py: Make package 'onelogin.saml2.utils' optional

- powerdnsadmin/routes/index.py
There is a missing local import since the removing of the global import from onelogin.saml2.utils
> Fix broken SAML login from 9c00e48f

- powerdnsadmin/models/domain.py
- powerdnsadmin/routes/api.py
Hello,
Since I quickly did a PR with a test branch, I closed it and reopen with a clean one. This patch applies the routine already existing in the GUI. There's a slight change that runs the pdns <> pda domain sync once in the end, rather than for each domain disassociation (if the account owns 20 domains and PDNS has hundreds of domains, the API call could be stuck for many seconds).
Regards
J
> Fix API Account deletion

- migrations/versions/fbc7cf864b24_update_history_detail_quotes.py
- powerdnsadmin/models/domain.py
- powerdnsadmin/routes/domain.py
#1160 removed some character replacement that are needed for databases with single quotes in the history table. 
Users with such entries in their history are not able to use PDA anymore. This small patch is for testing until a more robust solution is pushed.
Regards
> fix: Insert valid JSON in history.detail and replace single quotes in the database

- .gitignore
venv: in the wiki, the installation is described with creating the venv into "venv", but only ".venv" is in gitignore
yarn-error.log: file is created if yarn fails, it should not be commited to the repo accidentally
This is a preparation for some more pull requests of me soon.
> Adding venv and yarn-error.log to gitignore

- migrations/versions/6ea7dc05f496_fix_typo_in_history_detail.py
- powerdnsadmin/models/record.py
- powerdnsadmin/routes/admin.py
- powerdnsadmin/routes/domain.py
- powerdnsadmin/templates/applied_change_macro.html
There is a misspelling of rrset throughout the history logic, which also effects the json payload in the `history` database table. The migration will fix the existing payloads, so there is no need for backwards-compatibility and the code-change is a simple search-and-replace.
I am not really happy with the migration, but it is the best I could come up with to modify the json payload in a database-agnostic manner. Any suggestion are welcome.
> Fix rrest typo in history detail

- powerdnsadmin/routes/index.py
When a DynDNS request is submitted with an empty myip argument, and an X-Forwarded-For HTTP header is present, nothing is done. This fixes the issue.
> Fix DynDNS2 using X-Forwarded-For

- configs/development.py
- powerdnsadmin/routes/index.py
Added code in the index.py to not only pull the admin_user_group but also an operator_user_group. We then use this to assign those respective levels of access in PDNS-Admin, this means all we need to do is create a new user in JumpCloud and add them to the right group and they can log in without any need to tweak permissions in PDNS-Admin itself.
> Modification to SAML groups and group management

- powerdnsadmin/models/domain.py
* Previously the loop would always query the db even for none existing accounts
* Now cache previously looked up accounts and skip db queries for empty accounts
Loop time previously: 3.000699043273926 sec
Loop time now: 0.2798025608062744 sec
> Improve performance of domain update

- powerdnsadmin/models/record.py
Starting with the very first commit, the update was always done with two api calls: one for DELETE and one for REPLACE. It is however perfectly valid and save to do both at once, which makes it atomic, so no need for the rollback. Plus it only updates the serial of the zone once.
There is no point in sending the full RRset data when deleting it, the key attributes to identify it are enough. This also makes the behaviour consistent with the [api docs](https://doc.powerdns.com/authoritative/http-api/zone.html#rrset) where it says "MUST NOT be included when changetype is set to DELETE."
> Update zone using a single api call

- powerdnsadmin/routes/domain.py
Allow the new domain name to be input absolute (with a dot at the end). To keep the rest of the logic working as-is, remove it fairly early in the function.
Would have loved to use `str.removesuffix()` but that's python v3.9+ only.
> Allow new domains to be absolute

- powerdnsadmin/assets.py
- requirements.txt
- yarn.lock
This PR includes all 4 PR opened by dependabot. We know that we need to have a lot more work pending to update all libraries, but since it is not our priority, we can include these ones because they provide security fix.
Python `jsmin` is outdated and can't minify some regexp correctly. I switched to `rjsmin` which is ... say more recently updated. Note that it allows to use `npm install` and not yarn (which would not be required anymore) at a first glance. It has to be more tested though.
Using `npm install` with the provided `package.json`  and `jsmin` doesn't work because it resolves dependencies differently from yarn (i think that jquery fetched version is different) and encounter jsmin bug.
Fixes #1074
Includes #986 #1031 #1103 #1164
> Update Javascript libraries

- powerdnsadmin/models/record.py
PDNS checks that when a `CNAME` rrset is created that no other rrset of the same name but a different rtype exists. When changing a record type to `CNAME`, PDA will send two operations in one api call to PDNS: A deletion of the old rrset, and the addition of the new rrset. For the check in PDNS to pass, the deletion needs to happen before the addition. Before PR #1201 that was the case, the first api call did deletions and the second handled additions and changes. Currently the api payload contains additions first and deletions last. PDNS applies these in the order they are passed in the payload to the api, so to restore the original/correct/working behaviour the order of operations in the api payload has to be reversed.
fixes #1251
> Fix order of operations in api payload

- migrations/env.py
Fix Flask-Migrate ValueError from occurring when a password has '%' characters in it when specified via SQLALCHEMY_DATABASE_URI.
This resolves the issue described (and the solution from) [here](https://stackoverflow.com/questions/39849641/in-flask-migrate-valueerror-invalid-interpolation-syntax-in-connection-string-a).
% characters in the password need to be properly escaped, but only in the migrate script and not elsewhere. Tested and deployed this fix on my own deployment where it was necessary due to the use of auto-generated passwords on K8S.
> Fix handling of passwords with % in the SQLALCHEMY_DATABASE_URI

- powerdnsadmin/lib/helper.py
This change permits to proxy pdns zone notify api requests (which are expected to be with empty body)
[pdns api reference](https://doc.powerdns.com/authoritative/http-api/zone.html#put--servers-server_id-zones-zone_id-notify)
Solves #1265
> allow null/None JSON data (Used for pdns notifies via api and by LEGO-ACME v 4.9.0)

- powerdnsadmin/models/user.py
Resolves the following issue, which occurs with force_otp enabled
and OAuth authentication sources:
File "/srv/powerdnsadmin/powerdnsadmin/models/user.py", line 481, in update_profile
"utf-8") if self.plain_text_password else user.password
AttributeError: 'User' object has no attribute 'plain_text_password'
> models/user.py: properly guard plain_text_password property

- requirements.txt
Minor version bump. This is necessary to resolve build issues on Alpine 3.15+ or other OpenLDAP 2.5+ distributions.
When attempting to build with 3.4.0 on Alpine 3.15+ or any distribution using OpenLDAP 2.5+ (which should be all of them as OpenLDAP 2.4 is fully end of life,) the build of python-ldap will fail due to the python-ldap maintainers requiring re-entrant OpenLDAP and previously insisting users fix it by simply installing a totally different distribution.
python-ldap 3.4.2 finally saw the light and implemented a proper fix which handles both 2.4 and 2.5+.
Tested locally on Alpine 3.16.1, Rocky 8.5, and RHEL7 using a virtual environment, did not run into any issues.
> Update to python-ldap 3.4.2

- powerdnsadmin/models/user.py
This should work. It needs to be tested on a StartTLS setup as well.
I guess that these settings aren't even applied, as the [documentation says](https://www.python-ldap.org/en/python-ldap-3.4.2/reference/ldap.html#tls-options) that we have to call ldap.OPT_X_TLS_NEWCTX to make all the configurations effective, and it is not the case apparently.
At least, if removing this setting is harmless, it could be a quick fixup.
> Draft: Fix pyhton-ldap upgrade

- docker/Dockerfile
Alpine 3.13 is EOL, quick fix to get powerdns-admin running on alpine 3.15 :)
> Bump alpine to 3.17 in dockerfile

- migrations/versions/f41520e41cee_update_domain_type_length.py
- powerdnsadmin/models/domain.py
PowerDNS 4.7 is supporting 2 new zone types: "producer" & "consumer"
Due to the domain type is limited to 6 chars, PDA zone update will fail if producer or cusomer zones exist.
To solve this problem, this PR increases the lenght of the domain type to 8 chars.
This PR is the first step to support Catalog Zones in PDA (#1348)
> Support pdns4.7

- powerdnsadmin/templates/base.html
- powerdnsadmin/templates/login.html
Use SITE_NAME for upper left title on base page and login box title on login page (with default value).
This can be useful when using multiple powerdns admin in an organization.
> Use SITE_NAME as title

- powerdnsadmin/routes/index.py
as 2FA policies are typically enforced on the OAuth proviers end
Relates to #1051
> routes/index.py: otp_force shouldn't apply to OAuth

- powerdnsadmin/routes/domain.py
I moved pretty_ipv6_ptr setting retrieval out of record list loop. It's massive waste of resources when having large zones leading to unacceptable response time in UI.
example.com zone with 4000 records
Request URL: /domain/example.com
4000 queries hit SQL server: "SELECT setting.id AS setting_id, setting.name AS setting_name, setting.value AS setting_value FROM setting WHERE setting.name = 'pretty_ipv6_ptr'  LIMIT 1"
Browser "network" inspection:
19.49s (16.77s waiting for server response)
Same request and inspection report after this commit:
4.83s (2.54s waiting for server response).
Also related to issue #1009 (not resolving backend timeout, but still).
> Domain records list performance improvement - removing Setting.get query from loop

- powerdnsadmin/models/domain.py
- powerdnsadmin/models/setting.py
- powerdnsadmin/routes/admin.py
Introducing a new parameter to keep domain history intact in database. Current way is to remove history records by deleted domain_id, which is some environments isn't desired behaviour.
The default value of preserve_history is False and isn't a breaking change.
> Preserve domain records history after domain deletion

- powerdnsadmin/models/record.py
This merge request aims to fix a bug that exists in the auto_ptr logic.
The bug is that PowerDNS-Admin deletes PTR records when a user edits an A record without changing the name and content fields.
1. Find an existing A/PTR record pair. e.g. "www  in zone example.org -> 5.5.5.5" and "5 in zone 5.5.5.in-addr.arpa PTR www.example.com"
2. Edit the A record without changing the name or content, i.e. edit the comments or TTL fields.
3. Save and apply
The PTR record is still present after the changes are applied.
The PTR record is removed from the authoritative server.
The current behaviour of the auto_ptr function is to (re)add the corresponding PTR record, and then immediately delete it, leaving the reverse zone without the desired PTR record.
With the proposed fix, the order of operations …
> Changed auto_ptr() logic to remove-then-add

- configs/docker_config.py
Recently there was a PR merge where CAPTCHA_ENABLE environment variable was enabled by default, but it is easier to use if the user can disable it, so I made it changeable via environment variable.
> fix: configurable CAPTCHA_ENABLE env when docker use

- powerdnsadmin/routes/domain.py
- powerdnsadmin/templates/domain.html
There's a performance degrading setting verification in domain.html template records loop.
If the user is standard user and there's are a lot of records in the zone, the SQL backend gets a query 
`SELECT setting.id AS setting_id, setting.name AS setting_name, setting.value AS setting_value FROM setting WHERE setting.name = 'allow_user_view_history'  LIMIT 1` for every record.
While requesting simple in-addr.arpa zone with 256 records, SQL gets 268 indentical queries about allow_user_view_history. This issue has been in the template loop for ages. 
I added a simple variable to template rendering function and replaced Setting().get('allow_user_view_history') with a simple template variable check. SQL backend will be a lot happier.
> Standard user domain records list performance loop improvement

- powerdnsadmin/routes/dashboard.py
Stumbled into severe dashboard performance issue, when the following requirements are met:
- history table is big (e.g. 450k records)
- database engine is MySQL
- after login only standard user privileges are granted
MySQL isn't using indexes properly when joining large tables and "sort by" is causing massive filesort.  It isn't ok to fetch 175MB of data from mySQL to count the rows in python. Dashboard data fetching is split to two queries and by forcing "with index" for mysql, the execution was improved from 10 seconds to fractions of second.
```
use pda;
SET timestamp=1675927412;
SELECT history.id AS history_id, history.msg AS history_msg, history.detail AS history_detail, history.created_by AS history_created_by, history.created_on AS history_created_on, history.domain_id AS …
```
> Fix dashboard MySQL performance with large history for standard users

- powerdnsadmin/routes/admin.py
- powerdnsadmin/templates/base.html
Introducing Global Search feature for standard users too. As the API search call has no restriction, the results are filtered by allowed domain list for standard users. If standard user has a lot of domains to manage, this feature is a must have.
Operators/administrators search results won't be filtered.
> Global Search available for all users

- powerdnsadmin/templates/domain.html
If a record has a long content value, the table is scrollable and the action buttons are not visible until you scroll to the end.
This change breaks the content value (and the comment) to make the table fit on the screen.
Before:
After:
> Fixed scrolling on long content

- powerdnsadmin/templates/domain.html
Account for the hierarchical nature of DNS by sorting records in the zone view by their name, label-wise from right to left. Also justify the record names to the right, so they visually line up on label borders.
This uses the [object variant of the `data` column option](https://datatables.net/reference/option/columns.data#object).
> Sort records label-wise right to left

- powerdnsadmin/routes/admin.py
- powerdnsadmin/static/custom/css/custom.css
- powerdnsadmin/templates/admin_history.html
- powerdnsadmin/templates/applied_change_macro.html
The idea is to have a more fine-grained changelog where you can easily see on a per-field level if it changed, and what the old and/or new value is. Visual-vise I leaned on the common diff formats by using the `+` prefix with green colouring, and `-` with red colouring.
> Diff-ify changelog view for zone changes

- powerdnsadmin/lib/utils.py
- powerdnsadmin/routes/dashboard.py
- powerdnsadmin/templates/dashboard.html
I was playing around with zone tabs (or "custom boxes" as they were called) on the dashboard, and after writing docs it felt in need of a little cleanup. They are still hard-coded, but easily customised using a patch e.g. in a Dockerfile.
Fun fact: You can "hide" zones by adding a matching TabInfo to the `tabs` dict, but not add it to the `order` list.
* Rename `customBoxes` to be more descriptive and follow CamelCase name convention for classes
* Moved the class to the dashboard route where it is only used
* Change the tab info from a tuple to a named tuple
* Change all access to the tab info tuple from index to (new) property name
* Rename/Relabel the tabs
* Add docstrings
* Simplify the domain filter logic
* Simplify/Unify the tab html template
> Clean up dashboard zone tabs

- powerdnsadmin/models/setting.py
- powerdnsadmin/routes/admin.py
- powerdnsadmin/services/azure.py
- powerdnsadmin/services/github.py
- powerdnsadmin/services/google.py
- powerdnsadmin/templates/admin_setting_authentication.html
A new setting field has been added for each OAuth provider (Google, GitHub, and Microsoft) to allow the configuration of the server_metadata_url parameter of the authlib library being used for OAuth integration. The OpenID Connect OAuth provider already had this configuration option.
> Feature: Add OAuth Setting for Server Metadata URL

- requirements.txt
Fixes Python 3.11 incompatibility using ancient lxml binary PyPI built against old libxml2.
This fixes #1442 and closes #1433.
The issue with python3-saml not working is because the binary lxml wheel is built against a different version of libxml2.
``--no-binary lxml`` can be used to fix this and python3-saml will work.
for references check these:
- https://github.com/onelogin/python3-saml/issues/292
- https://bugs.launchpad.net/lxml/+bug/1960668
- https://github.com/open-formulieren/open-forms/pull/2247
```
Tested on:
- ubuntu:23.04 - WORKING
- ubuntu:22.10 - WORKING
- ubuntu:22.04 - WORKING
- ubuntu:20.04 - WORKING
- ubuntu:18.04 - NOT WORKING - pip usage error with -r requirements.txt
- debian:10    - WORKING
- debian:11    - WORKING
- alpine:edge  - WORKING
- alpine:3.17  - WORKING
- …
```
> Upgrade lxml & python3-saml dependencies with workaround

- migrations/versions/3f76448bb6de_add_user_confirmed_column.py
This change fixes the migration on the `user` table, `confirmed` column to be compatible with PostgreSQL and MySQL databases.
Fixes #635 which introduced a breaking change for MySQL databases and resolves #1446.
```
Tested on:
- PostgreSQL:14 - WORKING
- PostgreSQL:15 - WORKING
- MariaDB:10.11 - WORKING
- MariaDB:10.10 - WORKING
- MariaDB:10.9  - WORKING
- MariaDB:10.8  - WORKING
- MariaDB:10.7  - WORKING
- MariaDB:10.6  - WORKING
- MariaDB:10.5  - WORKING
- MariaDB:10.3  - WORKING
```
> Fix user confirmed column migration issue

- powerdnsadmin/models/setting.py
- powerdnsadmin/routes/admin.py
- powerdnsadmin/routes/index.py
- powerdnsadmin/routes/user.py
- powerdnsadmin/templates/admin_setting_authentication.html
- powerdnsadmin/templates/user_profile.html
- requirements.txt
Closes #989
I completely re-implemented https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/1054, which can be closed if this is merged. I did keep the values that were used as defaults.
Password policies are **opt-in** so we don't affect current installations.
I added password strength and complexity checking in a way it allows you to pick either or both of the methods, namely password character requirement counts and password complexity based on zxcvbn.
If either method is active, restrictions on using the username, password, email address, first name, last name will be set in place. I'm sure we can all agree unanimously on that!
I added help to the right hand side for the "Basic" tab in the "Authentication" settings to help with the fields being entered in.
Blanking the any password …
> Implement password strength & complexity checking

- powerdnsadmin/routes/index.py
It seems when logging in and logging out, then logging back in, setting the session timeout to 5 minutes, then waiting for expiry can cause a situation when using SQLA-based sessions which results in a NULL field in the database and causes a persistent 500 Internal Server Error.
As per issue 1439 here is a fix found by @raunz.
Resolves #1439.
Tested for about 8 hours and tons and tons of expired sessions, could not reproduce with the fix applied.
> Fix manual session clearing that triggered session expiration bug

- powerdnsadmin/models/user.py
- powerdnsadmin/templates/admin_setting_authentication.html
Previous behavior required the specification of all three group security groups before the "Save Settings" button would be enabled.
This adds a check into users.py which checks that the group is set before searching and removes the javascript preventing the specification of any combination of groups.
Tested:
- Tested all combinations on AD after MR 1238
- Tested all combinations on OpenLDAP
- Tested enabling the Group Security with no groups set which correctly prevents login
Resolves #1462
> Fix LDAP group restrictions by allowing the use of any combination of groups.

- powerdnsadmin/templates/admin_history.html
I looked at powerdnsadmin/templates/admin_history.html and the search form begins at L43 and should end with `</form>` at L204, but there's in an excessive `</form>` in between at L147.
As the `<form>` and `</form>` lines are in different div's, I moved `<form>` one level up and both div's building the search form are under single form entity. Tested with current dev release.
> Fix activity search invalid form markup causing submission failures

- powerdnsadmin/models/setting.py
- powerdnsadmin/routes/admin.py
- powerdnsadmin/services/azure.py
- powerdnsadmin/services/github.py
- powerdnsadmin/services/google.py
- powerdnsadmin/services/oidc.py
- powerdnsadmin/templates/admin_setting_authentication.html
Completed the removal of the OAuth JWKS URL setting as well as the update of how the existing metadata URL settings are being used.
For additional information, reference GitHub issue #1499.
> OAuth Settings Updates

- powerdnsadmin/routes/domain.py
- powerdnsadmin/templates/domain_add.html
- powerdnsadmin/templates/domain_setting.html
This PR makes it possible to use a different Zone Type than "native". It also moves the input field for primary IP's just below the Secondary radio button when adding a zone. This makes it more clear that this field is related to the zone being a secondary.
> Fix Zone Type can not be changed from "native" when adding or modifying zones

- powerdnsadmin/routes/dashboard.py
The dashboard.domains_custom route was hardcoded to either return all the domains, or at most 100, regardless of default_domain_table_size setting.
Make this limit be dependent on default_domain_table_size instead.
The API will now limit to 100 or default_domain_table_size, whichever one is higher. This is done to not break any seconday use-cases that might depend on the hardcoded setting.
> Feature Update: Allow more than 100 rows in the zone list view.

- powerdnsadmin/templates/admin_edit_account.html
…use all unassigned zones to be selected automatically following the attempt of account creation with an invalid name.
> Fixed issue with all unassigned zones being selected after a new account's name fails to validate

- powerdnsadmin/templates/base.html
- powerdnsadmin/templates/domain.html
These are changes that will prompt a card at the top of the zone editor the moment a change is detected. That modal will then continue to scroll with the user down the page to always show that there are unsaved changes. If a user also tries to navigate away while there are unsaved changes, there is a second modal that will pop up with the options to stay or leave.
> Indicate Unsaved Changes

- powerdnsadmin/static/assets/css/roboto_mono.css
- powerdnsadmin/static/assets/css/source_sans_pro.css
I updated the following files to use relative font file path references as opposed to the absolute paths that had been used;
- powerdnsadmin/static/assets/css/roboto_mono.css
- powerdnsadmin/static/assets/css/source_sans_pro.css
> Update static fonts to use relative paths instead of static

- powerdnsadmin/models/user.py
- powerdnsadmin/routes/index.py
I have updated the create_local_user() function to be case sensitive when checking the database for existing users with the same username and/or email. Additionally, when this function fails it returns its result status and message, as this message is useful for debugging, I have added it to the log message.
> Fixes local user setup to perform case-insensitive verification of existing usernames / emails

- powerdnsadmin/routes/index.py
I updated the `powerdnsadmin/routes/index.py` router method `register_modules` to use the `Blueprint.record_once` event in-place of the deprecated `Blueprint.before_app_first_request` event.
> Update index router to replace the use of the deprecated `before_app_first_request` event with `record_once`

- powerdnsadmin/routes/domain.py
I updated the line `if not rrsets and domain.type != 'slave':` in `powerdnsadmin/routes/domain.py` to be `if not rrsets and str(domain.type).lower() != 'slave':` in order to resolve false positives due to case differences in the referenced values.
> Updated zone type comparison logic in domain router to be case-insensitive

- powerdnsadmin/models/domain.py
- powerdnsadmin/static/custom/js/custom.js
- powerdnsadmin/templates/dashboard.html
I updated UI code for the dashboard view of zones as well as associated back-end methods to perform URL encoding on the zone name before using it in requests where the value is part of the URL path. The lack of this was causing zone names with forward slashes to fail during related requests.
> Fix zone name encoding for UI XHR requests as well as requests to the PDNS API

- powerdnsadmin/models/user.py
I added a new function called `escape_filter_chars` in the `powerdnsadmin/models/user.py` model and applied it's use at the beginning of the adjacent `ldap_search` method of the user model.
> Added LDAP search filter cleansing mechanism to properly escape special characters

- powerdnsadmin/models/user.py
My previous PR broke LDAP altogether and this should presumably fix it based on user feedback.
> Fixing new LDAP search filter cleansing mechanism to only target user DN value returned on AD connections

- requirements.txt
Closes: #1739 
Pip Changes:
- Jinaj2 - `3.1.3` - upgrade from `3.1.2`
- certifi - `2023.11.17` - downgrade from `2023.12.17`
- cryptography - `42.0.2` - upgrade from `39.0.2`
- requests - `2.31.0` - upgrade from `2.28.2`
- werkzeug - `2.3.8` - upgrade from `2.2.3`
> Updated Pip Dependencies (Jinaj2, certifi, cryptography, requests, werkzeug)

- yarn.lock
Closes: #1741 
- crypto-js from `4.1.1` to `4.2.0`
> Updated NPM dependencies (cryto-js)

- powerdnsadmin/templates/admin_setting_authentication.html
Resolves #1745
Updated the `mail` reference to `email`.
> Corrected Azure authentication scope documentation

- docker/Dockerfile
- powerdnsadmin/models/sessions.py
- powerdnsadmin/routes/admin.py
- powerdnsadmin/routes/api.py
- powerdnsadmin/routes/dashboard.py
- powerdnsadmin/routes/domain.py
- powerdnsadmin/routes/index.py
- powerdnsadmin/routes/user.py
Updated the Sessions model reaper functionality to actually function correctly.
Additionally, I added a call to execution for the session reaper to each router's `@domain_bp.before_request` trigger.
I created a `/healthcheck` route that simply returns 'ok' which also expires it's session immediately. Accordingly, I updated the Dockerfile to reference this healthcheck path.
> Corrected Session Reaping / Docker Health Check
